# Generated by Django 4.2.4 on 2023-08-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(default=None, max_length=3000),
            preserve_default=False,
        ),
    ]
