# Generated by Django 4.2.4 on 2023-08-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
    ]
