# Generated by Django 4.2.4 on 2023-08-09 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_like_related_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='related_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post'),
        ),
    ]
