# Generated by Django 4.2.4 on 2023-08-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_like_related_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
